name: syncopate
description: "Sync, standardize, and transfer playlists between Apple Music and Spotify."
publish_to: 'none'


# major.minor.patch+build
version: 0.0.1+1


environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true